/**:
    ros__parameters:
      video_device: "/dev/bob_cam_4"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 640
      image_height: 480
      camera_name: "bob_cam_1"
      camera_info_url: "package://bob_base_bringup/config/cam_4/camera_info.yaml"